development:
  adapter: postgresql
  encoding: utf8
  database: babs2_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: babs2_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: bab2_production
  pool: 5
  username:
  password:
